language: node_js
node_js:
  - "0.12"

install:
 - npm install
 - bower install

before_script:
 - chmod +x ./deploy.sh

script:
 - gulp doc

after_success:
 - bash ./deploy.sh

env:
  global:
  - GH_REF: github.com/fluanceit/angular-dashboard.git
  - secure: "Z5qdPYfrqQJHE9I0GIrogcJ7AupH4f+KYj5ZzFk83yxyXFrM1NlQMsky43KCbIDJcro2+sNRh/XtjLXjiDT3jIY5+xEefX+prTIQLSSbs11caQYRauaGZKsXHb9gnp9Gfc98x+e9KkBRN8jOy8BL4SSiYSsU7YVXGM9T+aLPcsk++PfK0qRtC/Nr6O16yQodGIG+u/bMzCzM2ghu3mhcXGkOb/MXR1El2v+/AgiBTB7R8U1TuPZSCFbsYpRQ5D6ypwfTCPUdt75qgCtVnuNcjdVGHs1zJZYZqtzc/3HmXUsk5vbkwaNmF9C2n/cwVZfjnBkhcO0y/pAn4+GM8CaN6lbsmRfcbfIV2/24PwcIrZtrSAIPqBVJwyOKcngKx8g8bm46GwD2z2nEdXVCntBG83YwtKilNZsm5HjFjcAjNTCbd6VhG6WtsVpUAgi8i+1+6UtXIqAC+etNGWMBuz9+rWujG5Grsy9Y8WmI8qgz4nsrl1qaWFOxl5SPhQgyBYn/DwJI49L7MTuuNjyMfsCPC9PbvISKfWAKUiuhaJT0Y8M/7u+yvt/jBL18SFbohgGCwwUw8Ptyd8iR5pZTxfcC5GdurJMr/d6TIqOgRwZ12knMCrWgshUAyEEvsr82L5pwOeAUr5guKFtd//Ek40LipmrRbFD7b9sG7WiU05TzNIQ="
