language: node_js
node_js:
- '0.12'
install:
- npm install
- bower install
before_script:
- chmod +x ./deploy.sh
script:
- gulp doc
after_success:
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/fluanceit/angular-dashboard.git
  - secure: dSB0meUNjsUkRi373cKLJBj0SjiJ1cNVxrYHy2N4uYbWzK9UHJCfFdMc785z8allPpMsZYs+0LuA251zde17SnXr7fLuyMYAgAqMYcan6gLxH8JxbAPsBpwisL/Poer6M1/ZQAXCm1xG/kYkSNgF+RLya/sdi2BXax7pgfi76tuJizEcL2p0QzUkoBJ8dln1nX0F99r0zTnEsQ094/SISyGxNmIAmoO2JSXWCSv2JQCAq4BtmfNTcSwXgNiL2OvOclJ64OPc0dy4kJVrrt6aeQXiTf5A9rtQDFTI0PO6OuWO8UWzIt1aR9Dd79xb+QhGxV5y2Wmh/siH27emwUKQ4p7lgP35XBj0ckXKmeKNwTRVA4dfiSR3pZSB8B6kRvtLnuE0IwZyrkrStcsyV22tZ9Bp3OUkeT85KIQxHB8XjSRykM1teKyTzTsq/Ha+icbwGZQMJZWR+m8GuzpjFHGcZhVwNtUKall3yK7NMMhHsEHgMJquBZuxgr1hAOC4mwF+sep4FZjNrFkJlI62xXjSN2zpvfTSmnf/PZDBZnLT/MPVnXQNWUVfFPVNgDA7353oC6vUqQuObI0kzGxIqD/QL301Rf5g7c8AoLL+XajCe5NeT4VZUlCyXZyZ3tHuAjqQLv0HSp6etia5d7c6juGWDXHQ0NZb6fqC9ujeae1pgQs=
