language: node_js
node_js:
  - "0.12"

install:
 - npm install
 - bower install

before_script:
 - chmod +x ./deploy.sh

script:
 - gulp test
 - gulp doc

after_success:
 - bash ./deploy.sh

env:
  global:
  - GH_REF: github.com/fluanceit/angular-dashboard.git
  - secure: "hb623SCc/V8T2g8YT5PWXKRLCDMMDfqg2W6u7txCIBhuT7x5nvjnbNAqpvQTV7NenyaEM9QIQq6SmcI32tzZFxiLxyTip5mxife1Feqm/76KQJq9zBq2fCbW07a5rY29daDMfEjUS4Wcn9EK2SNfTAqHywRz/4EiH9SZts7lDTbIis30Znc6n8H6b/QXtJimVmQgtqdJb4CDea1FnhWp9FOoaColYUsMKlkc9FrTjOTwkb1q7D1QfwEak1fk2jOKioksQx4IqDj1z0Y1UpNdQ+4SpbOCo0qBerLiV3mmmZyXUMmpRzDWayh30tF++H1OmyqW4niwwljy+1viPRxis/kJN1WUe35n08+Q95nhKDtEG46AHlorG/LnwXlWeW2m8jQIYCU/csS/D86rjBXM9mHEMUVu60flZPcY8vV3S0ic2SoVlrLR37wsucGopPmRPM9d03b3/1ppmfWRELj/zfqn8dRlmuGIft+rXdwYN5a9e1Ow7MC+KmIytDJ85rCchPKZ7zoUwabFTWIylJeutX7MuDt5xKMxs6q9eTORA0MYrJF5S6RfX7JtOgvenaZSpO7ynhR76n1IH1/CcIwjyf00h790+faBjF5r8VxpAcfZX5q217XL05Xx7JBQ+1AoH7jwQjqZnIm4Or3OInlrA0mGeAKzOVwfzEVWotWoBL0="
