language: node_js
node_js:
- '0.12'
install:
- npm install
- bower install
before_script:
- chmod +x ./deploy.sh
script:
- gulp test
- gulp doc
after_success:
- bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/fluanceit/angular-dashboard.git
  - secure: D8i5M2a0l23+girYvNa7kbdfHX0307fQr61WtoDOl+C12kr9zmxYlULLymYN2vQ7udTM5Ikc6X6FKAFl1rzxmV0F6zK6I3YHTam4avMA6b6pgop5B30FT2rt7/vOzW6SUK/yJM983vHLwBY/qWyvGOtEwqiZOI07MYpFIwO2vYQl6eCTCOSWvayEa073vvpc1LjOWthYRyxETAALZ9aSEn1DYh8JeIuqMoCWLSgrOQDyvTK6ucss3nKDhCVSrlFe4s1ye6rln+TL0sdaQNK61//zs5l/7CK52B2TQL13bPtYP4Hx0/lYV++zNKtY8t4lUSCSQcHszYbXqMcvS+xhMHq7vI0ce7lYK931VndiU8O588JVWMzso83nsfO+aGiXU2kvO8Hx605AcIKbCj8RS7I7gOG4TDDkczGqv6oPVNXFQpLstkHzO20sB36jAuzz/GBFARIYjinq6Le8EUy6HUBPFYVTZdxm6QTf4Cm4CuclIKP8DrPe1tQSFoVDR/kZubOrh1i3Z5JV8XisU66Xh2H5AhH1cMnO+RpuNokoKx2Ii1m5ZcP1qmO1VFVceowdl1dGtSg39jb/18vhWKKT371JkfmXgTn5I9s+ZOZkfd7tmByxU9/A7L50PKGrouxKYbK3beqEfxZ204y1kqmKISJJrX4aUP9UjXatxoE2tRs=

